// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run over the direct connection — PgBouncer's transaction
    // pooler (DATABASE_URL) doesn't support the prepared statements Prisma
    // Migrate needs.
    url: process.env["DIRECT_URL"],
  },
});
